import { index, primaryKey, sqliteTable, text, integer, uniqueIndex } from "drizzle-orm/sqlite-core";

export const events = sqliteTable("events", { id: text("id").primaryKey(), title: text("title").notNull(), createdAt: text("created_at").notNull() });
export const slots = sqliteTable("slots", { id: text("id").primaryKey(), eventId: text("event_id").notNull(), startsAt: text("starts_at").notNull(), endsAt: text("ends_at").notNull(), sortOrder: integer("sort_order").notNull() }, (table) => [index("idx_slots_event_id").on(table.eventId)]);
export const responses = sqliteTable("responses", { id: text("id").primaryKey(), eventId: text("event_id").notNull(), name: text("name").notNull(), createdAt: text("created_at").notNull() }, (table) => [index("idx_responses_event_id").on(table.eventId)]);
export const answers = sqliteTable("answers", { responseId: text("response_id").notNull(), slotId: text("slot_id").notNull(), status: text("status", { enum: ["yes", "maybe", "no"] }).notNull() }, (table) => [primaryKey({ columns: [table.responseId, table.slotId] })]);

export const scheduleEvents = sqliteTable("schedule_events", { id: text("id").primaryKey(), title: text("title").notNull(), durationMinutes: integer("duration_minutes").notNull(), stepMinutes: integer("step_minutes").notNull(), createdAt: text("created_at").notNull() });
export const scheduleWindows = sqliteTable("schedule_windows", { id: text("id").primaryKey(), eventId: text("event_id").notNull(), startsAt: text("starts_at").notNull(), endsAt: text("ends_at").notNull(), sortOrder: integer("sort_order").notNull() }, (table) => [index("idx_schedule_windows_event_id").on(table.eventId)]);
export const scheduleResponses = sqliteTable("schedule_responses", { id: text("id").primaryKey(), eventId: text("event_id").notNull(), name: text("name").notNull(), normalizedName: text("normalized_name"), createdAt: text("created_at").notNull(), editTokenHash: text("edit_token_hash") }, (table) => [index("idx_schedule_responses_event_id").on(table.eventId), uniqueIndex("idx_schedule_responses_event_normalized_name").on(table.eventId, table.normalizedName)]);
export const scheduleResponseDays = sqliteTable("schedule_response_days", { id: text("id").primaryKey(), responseId: text("response_id").notNull(), windowId: text("window_id").notNull(), state: text("state", { enum: ["full", "custom", "unavailable"] }).notNull() }, (table) => [index("idx_schedule_response_days_response_id").on(table.responseId), index("idx_schedule_response_days_window_id").on(table.windowId)]);
export const scheduleAvailabilityRanges = sqliteTable("schedule_availability_ranges", { id: text("id").primaryKey(), responseDayId: text("response_day_id").notNull(), startsAt: text("starts_at").notNull(), endsAt: text("ends_at").notNull() }, (table) => [index("idx_schedule_ranges_response_day_id").on(table.responseDayId)]);
